{% set name = "DeepSpectrum" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DeepSpectrum/{{name}}/archive/v{{ version }}.tar.gz
  sha256: 6579fcab2a0fa9b7e7dd3deb538b38d3d4c1b34f7c18fb77f3f2bc61c9a8db65
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - deepspectrum = deepspectrum.__main__:cli


requirements:
  build:
    - python>=3.6 # [not osx]
    - python 3.6.* # [osx]
    - setuptools

  run:
    - python>=3.6 # [not osx]
    - python 3.6.* # [osx]
    - mesa-libgl-cos6-x86_64 # [linux]
    - click>=7.0
    - ffmpeg # [win]
    - imread>=0.7.1
    - librosa>=0.6.3
    - matplotlib>=3.0.3
    - numpy>=1.16.3
    - opencv>=4.1.0
    - pillow>=6.0.0
    - scipy>=1.2.1
    - tensorflow-gpu>=1.13.0 # [linux]
    - tensorflow>=1.13.0 # [not linux]
    - tqdm>=4.32.1

test:
  source_files:
    - tests/*
    - examples/*
  imports:
    - deepspectrum
  requires:
    - pytest>=4.4.1
    - pytest-cov>=2.7.1
  commands:
    - pytest -vv --cov deepspectrum tests/

about:
  home: https://github.com/DeepSpectrum/DeepSpectrum
  license: GPL v3
  license_file: LICENSE
  license_family: GPL
  dev_url: https://github.com/DeepSpectrum/DeepSpectrum
  summary: 'A tool for extracting deep CNN-descriptors from audio data.'

extra:
  recipe-maintainers:
    - DeepSpectrum
    - mauricege