{% set name = "DeepSpectrum" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DeepSpectrum/{{name}}/archive/v{{ version }}.tar.gz
  sha256: d8c99293357e9a3ec7686da56a016344c15cca0faf6ede283eb2d9ca24408806
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - deepspectrum = deepspectrum.__main__:cli


requirements:
  build:
    - python>=3.6.0 # [not osx]
    - python=3.6.* # [osx]
    - setuptools
  run:
    - python>=3.6 # [not osx]
    - python=3.6.* # [osx]
    - mesa-libgl-cos6-x86_64 # [linux]
    - click>=7.0
    - ffmpeg # [win]
    - imread>=0.7.1
    - librosa>=0.6.3
    - matplotlib>=3.0.3
    - numpy>=1.16.3
    - opencv>=4.1.0
    - pillow>=6.0.0
    - pytorch-cpu>=1.1.0 # [not osx]
    - torchvision-cpu>=0.3 # [not osx]
    - pytorch>=1.1.0 # [osx]
    - torchvision>=0.3 # [osx]
    - scipy>=1.2.1
    - tensorflow>=1.12.0 # [not linux]
    - tensorflow-gpu>=1.12.0 # [linux]
    - tqdm>=4.32.1

test:
  source_files:
    - tests/*
    - examples/*
  imports:
    - deepspectrum
  requires:
    - pytest>=4.4.1
    - pytest-cov>=2.7.1
  commands:
    - pytest -vv --cov deepspectrum tests/ # [not linux]

about:
  home: https://github.com/DeepSpectrum/DeepSpectrum
  license: GPL v3
  license_file: LICENSE
  license_family: GPL
  dev_url: https://github.com/DeepSpectrum/DeepSpectrum
  summary: 'A tool for extracting deep CNN-descriptors from audio data.'

extra:
  recipe-maintainers:
    - DeepSpectrum
    - mauricege