{% set name = "DeepSpectrum" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DeepSpectrum/{{name}}/archive/v{{ version }}.tar.gz
  sha256: 5acf69f48bfb88a931f2cddc984a8a97a7866992a59603718e554c840f113b9f

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - deepspectrum = deepspectrum.__main__:cli


requirements:
  build:
    - python >=3.6,{{PY_VER}}*
    - setuptools

  run:
    - python {{PY_VER}}*
    - click>=7.0
    - imread>=0.7.1
    - librosa>=0.6.3
    - matplotlib>=3.0.3
    - numpy>=1.16.3
    - opencv>=4.1.0
    - pillow>=6.0.0
    - scipy>=1.2.1
    - tensorflow-gpu>=1.12.0
    - tqdm>=4.32.1

test:
  source_files:
    - tests/*
    - examples/*
  imports:
    - deepspectrum
  requires:
    - pytest>=4.4.1
    - pytest-cov>=2.7.1
  commands:
    - pytest -vv --cov deepspectrum tests/

about:
  home: https://github.com/DeepSpectrum/DeepSpectrum
  license: GPL v3
  license_file: LICENSE.md
  license_family: GPL
  dev_url: https://github.com/DeepSpectrum/DeepSpectrum
  summary: 'A tool for extracting deep CNN-descriptors from audio data.'

extra:
  recipe-maintainers:
    - DeepSpectrum
    - mauricege