github:
  user_or_org: DeepSpectrum
  repo_name: deepspectrum-feedstock
channels:
  sources:
    - conda-forge
    - defaults
  targets:
    - ["DeepSpectrum", "main"]
travis:
  secure:
    BINSTAR_TOKEN: MKssfgauqxRzcyEsJXffz9E8dJsHpO0tDfJiVySidhwMXBiuexhsjU4cJbcJEO+kvmK10WhzLCbOVhM6Wjy4udX+sQcIGlO4AgDjEcMkUd0HTOjDXGhvdQr6l3eJ55Isvn9RAFXilzyc8dqNd0DUgvg65glmOLQDbdIb2w3GKKg45epTFyuqTEI/5rGdj9GEw1tJcyh8XgD+ZiZkzJWQWPc1xXuOvIGsaTdJm2r3jW11Dss3TosQ/ypoVjmwZV67jtJHJ681BMdgkABPBOSCO6QD5P2+O6mxxbbG0MnkOkyraA2i5EMBYiI+g7z8PC7YIqvOJo4+oopqnN4CFeMyV0selOOY0f/PJGLUYdsvUjaHLk7tyCQHCfQqoa1f3rxLP0WRySq0FrNFIYFiT4c1TgjOG8s+WOhnWw/6ZIHrZoYtXlkoSWSxu/2wCbrmCOA0cInog6nIsXb04vlH8a1YSxvKD/YPU8FJ+GULDdt7iMsX9Vg8MWq5/wBiT8XL0weqZfDBBO484DKjKjRha3v81PGemqjUEIdev5sZF+SzKpSe1prWIMX6nfhOPgr8nmedciIWKB2RuvCTGWunvp71zrhV89kl7P0cvumwY/7tICHM3MTWzSmAFYaPZV4Wk3GvW3NxmlrVBNixOY+ykphNvTN41+j+u3HmRepSmhTtaak=
provider:
  osx: travis
  linux: circle
  win: appveyor
  linux_aarch64: None
  linux_ppc64le: None
appveyor:
  secure:
    BINSTAR_TOKEN: GQWbR7p2RUuwc3g2INvq/bMx27HdaL0OmmkP4Tur59I=
azure:
  upload_packages: False
  force: False