github:
  user_or_org: DeepSpectrum
  repo_name: deepspectrum-feedstock
channels:
  sources:
  - conda-forge
  - defaults
  targets:
  - [DeepSpectrum, main]
provider:
  osx: travis
  linux: travis
  win: appveyor
  linux_aarch64: None
  linux_ppc64le: None
azure:
  upload_packages: false
  force: false
travis:
  secure:
    BINSTAR_TOKEN: Z1vI+8LPhuwtK2Sr4dfUO9/Rvi5lBp1rzibBvXKaAbEMaYeaqcc4WeJ3dGjntrxWhzIzWcVLDBB29TuIjLsOtKMA9y+I476AwYtyRK44i6XgXmHiWZPOZhyn93CHJfq/tILsNsXzyI2Adu7Q0EAKywOMC1M59XTcUbVEPScwLOOD1jg1BlPJiGbAeR1R2PxoSlewD8drvqeKPmR3koFl+veZ5oa1oXUDy+86jcBRjrGMRB4U9HjkgEw6ADgcjqWBVxY3chIXExO2s+j4RLJQTPwKg76RujvULg+2FrKlHy4hyIOFahgkDNgmpExOSvsWdsX1aFVX9990z+JytgKAo12G6pC7viKCGkGzSM4tkt31oyw2KnzveC46ZCp5b34AHN12iK5lsAvC2YMQUwQrpCseRsJlkMW1iSVAosDTU3ErdCOVgYIDvqQ3z1zw8qEWtVJiESizp2Zm5a+9lQWvoRnbXKi4Z3R0jTY65PVMwxx+3CTV+XtXKP3FX1SvZAR2YOAUWXaSRz469hsRZQ33JkKP3UPWhYE8s+QbyyIYkzJuJkaUAHljLG1qqLuWbkJGfwLtGjEaHOQy8RZzjr0qx+smqmk6hirwhKIyjLRLYse3oWAEcPnaRzVD3yn6NGM1nAWHyCjqf012fSVVRIXd2fM7xJ/0/YuGMrhqh2JVpvo=
appveyor:
  secure:
    BINSTAR_TOKEN: vHnzv5MZIj7aLMjUP3vE/ySuXpID44XYdl/NxfdBT3E1QPBqewcxFIeF7bs5Pu6Z
